/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PartyNewImport } from './routes/party/new'
import { Route as PartyIdImport } from './routes/party/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PartyNewRoute = PartyNewImport.update({
  id: '/party/new',
  path: '/party/new',
  getParentRoute: () => rootRoute,
} as any)

const PartyIdRoute = PartyIdImport.update({
  id: '/party/$id',
  path: '/party/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/party/$id': {
      id: '/party/$id'
      path: '/party/$id'
      fullPath: '/party/$id'
      preLoaderRoute: typeof PartyIdImport
      parentRoute: typeof rootRoute
    }
    '/party/new': {
      id: '/party/new'
      path: '/party/new'
      fullPath: '/party/new'
      preLoaderRoute: typeof PartyNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/party/$id': typeof PartyIdRoute
  '/party/new': typeof PartyNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/party/$id': typeof PartyIdRoute
  '/party/new': typeof PartyNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/party/$id': typeof PartyIdRoute
  '/party/new': typeof PartyNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/party/$id' | '/party/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/party/$id' | '/party/new'
  id: '__root__' | '/' | '/party/$id' | '/party/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PartyIdRoute: typeof PartyIdRoute
  PartyNewRoute: typeof PartyNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PartyIdRoute: PartyIdRoute,
  PartyNewRoute: PartyNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/party/$id",
        "/party/new"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/party/$id": {
      "filePath": "party/$id.tsx"
    },
    "/party/new": {
      "filePath": "party/new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
